# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux misc drivers.
#

obj-$(CONFIG_AW_RFKILL)      += sunxi-rf/
obj-$(CONFIG_AW_MACADDR_MGT)    += sunxi-addr/
obj-$(CONFIG_AW_BOOTEVENT)   += sunxi-bootevent/
obj-$(CONFIG_SUNXI_DIRECT_GPIO) += sunxi-direct-gpio.o
obj-$(CONFIG_SUNXI_TVUTILS_SCRIPTS)   += sunxi-tvutils/
obj-$(CONFIG_SUNXI_LED_BCT)   += leds/
obj-$(CONFIG_AW_GPIO_MOTOR_2803)   += sunxi-gpio-motor/
obj-$(CONFIG_AW_IRCUT)   += sunxi-ircut/
obj-$(CONFIG_AW_FLASHAPP)   += flash_app/
obj-$(CONFIG_AG_LINK) += aglink/
obj-$(CONFIG_AW_STARTUP_INFO) += sunxi-startup-info/

obj-y += sunxi-fastboot/
