# SPDX-License-Identifier: GPL-2.0

# Minimal System
obj-y += clk/
obj-y += pinctrl/
obj-y += uart/
obj-y += timer/

# Basic System
obj-y += dma/
obj-y += rtc/
obj-y += bus/
obj-y += dumpreg/
obj-y += watchdog/
obj-y += iommu/
obj-y += mbus/
obj-y += aw_trace/

# Storage
obj-y += mmc/
obj-y += ufs/
obj-y += mtd/
obj-y += redeposit/

# Graphics
obj-y += video/
obj-y += g2d/
obj-y += di/
obj-y += vin/
obj-y += vfe/
obj-y += tvd/
obj-y += drm/
obj-y += gpu/
obj-y += car_reverse/
obj-y += tvin/

# Multi-Media
obj-y += ve/
obj-$(CONFIG_VIDEO_RT_MEDIA) += rt-media/

# Audio
obj-y += sound/

# Security
obj-y += ce/
obj-y += smc/
obj-y += sid/
obj-y += secure_storage/
obj-y += drm_heap/

# I/O Connectivity
obj-y += wupio/
obj-y += pcie/
obj-y += phy/
obj-y += emac/
obj-y += gmac/
obj-y += stmmac/
obj-y += usb/
obj-y += twi/
obj-y += spi/
obj-y += spi-ng/
obj-y += ledc/
obj-y += pwm/
obj-y += ir-tx/
obj-y += ir-rx/
obj-y += gpadc/
obj-y += lradc/
obj-y += rtp/
obj-y += input/
obj-y += ata/
obj-y += smartcard/
obj-y += wiegand/
obj-y += iio/

# Power Management
obj-y += irqchip/
obj-y += standby/
obj-y += thermal/
obj-y += nvmem/
obj-y += pm_domain/
obj-y += power/
obj-y += powercap/
obj-y += cpufreq/
obj-y += devfreq/
obj-y += dsufreq/
obj-y += riscv_pm/

# AMP/XPU
obj-y += amp_timestamp/
obj-y += msgbox/
obj-y += hwspinlock/
obj-y += remoteproc/
obj-y += rpmsg/
obj-y += rpbuf/
obj-y += npu/

# Hyper
obj-y += hyper/

# aglink-gyro
obj-$(CONFIG_AG_GYRO_USE) += misc/aglink_gyro/

# Misc
obj-y += misc/
obj-y += vendor_hooks/
obj-y += touch_boost/
obj-y += chips/

# Wireless
obj-y += net/
obj-y += bluetooth/

# Debugging
obj-y += crashdump/
obj-y += jtag/
obj-y += debug/

# pstore
obj-y += pstore/

# FS
obj-y += fs/

obj-y += ansc_adaptor/

# carveout
obj-y += dma-buf/

obj-y += staging/android/ion/heaps/

#cpu_ecc
obj-y += cpu_ecc/

# local bus
obj-y += lbc/

#sram_ecc
obj-y += sram_ecc/

#sched
obj-y += sched/

#motor and motor-limiter
obj-y += motor/
obj-y += motor-limit/
