# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the drm heap drivers.
#

obj-$(CONFIG_AW_ANSC_CMA_NON_CACHE) += cma_non_cacher.o
obj-$(CONFIG_AW_ANSC_DMA_ADAPT) += dma_ops_adapter.o
obj-y += kasan/
